CREATE TABLE IF NOT EXISTS Customers
( CustomerID INT UNSIGNED NOT NULL AUTO_INCREMENT PRIMARY KEY,
  Name CHAR(50) NOT NULL,
  Address CHAR(100) NOT NULL,
  City CHAR(30) NOT NULL
);

CREATE TABLE IF NOT EXISTS Orders
( OrderID INT UNSIGNED NOT NULL AUTO_INCREMENT PRIMARY KEY,
  CustomerID INT UNSIGNED NOT NULL,
  Amount FLOAT(6,2),
  Date DATE NOT NULL,
  FOREIGN KEY (CustomerID) REFERENCES Customers(CustomerID)
);

CREATE TABLE IF NOT EXISTS Books
( ISBN CHAR(13) NOT NULL PRIMARY KEY,
  Author CHAR(50),
  Title CHAR(100),
  Price FLOAT(4,2)
);

CREATE TABLE IF NOT EXISTS Order_Items
( OrderID INT UNSIGNED NOT NULL,
  ISBN CHAR(13) NOT NULL,
  Quantity TINYINT UNSIGNED,
  
  PRIMARY KEY (OrderID, ISBN), /* Se una tabella ha una chiave primaria multipla va specificata in questo modo e non a fianco del singolo campo*/
  FOREIGN KEY(OrderID) REFERENCES Orders(OrderID),
  FOREIGN KEY(ISBN) REFERENCES Books(ISBN)
);

CREATE TABLE IF NOT EXISTS Books_Reviews
( ISBN CHAR(13) NOT NULL PRIMARY KEY,
  Review TEXT,
  
  FOREIGN KEY(ISBN) REFERENCES Books(ISBN)
);